name: fluttertempv2
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  dartz: ^0.10.1
  intl: ^0.17.0
  dio: ^4.0.6
  http: ^0.13.4
  get_it: ^7.2.0
  provider: ^6.0.2
  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  connectivity_plus: ^2.3.0
  permission_handler: ^9.2.0
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true
